// Package storage abstracts the object storage backend used for media
// assets (plan.md section 10.5 / 16). PostgreSQL stores only metadata and
// references; the actual files live here. The interface is deliberately
// storage-agnostic so MinIO (self-hosted, default for local/staging) can be
// swapped for a cloud bucket in production without touching callers.
package storage

import (
	"context"
	"io"
	"time"
)

// ObjectInfo describes a stored object.
type ObjectInfo struct {
	Key         string
	SizeBytes   int64
	ContentType string
}

// Store is the abstract object storage backend for media assets.
type Store interface {
	// Put uploads content under the given key. The key is generated by the
	// backend (never derived from user input) so it cannot leak personal
	// data or be guessed.
	Put(ctx context.Context, key string, content io.Reader, size int64, contentType string) (ObjectInfo, error)

	// Get retrieves an object's content. Callers must close the returned reader.
	Get(ctx context.Context, key string) (io.ReadCloser, error)

	// Delete removes an object. Deleting a non-existent key is not an error.
	Delete(ctx context.Context, key string) error

	// PresignedGetURL returns a short-lived URL for direct download, used by
	// the production distribution path (plan.md section 16.7). Self-hosted
	// MinIO in the MVP can also use this; the API-proxied download path is
	// the fallback when presigned URLs are not desired.
	PresignedGetURL(ctx context.Context, key string, expiry time.Duration) (string, error)
}
